- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - build-essential
      - python-setuptools
      - python3-setuptools
      - python-pip
    state: present
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx={{ docker_version }}
    state: present

- name: Ensure Nginx is started and enabled at boot.
  service:
    name: nginx
    state: started
    enabled: yes
